import dash
import dash_bootstrap_components as dbc
from dash import Input, Output, callback, dcc, html

from components.ops_page_shell import data_table, info_card, kv_grid, page_shell, section
from services.dataset_selection import resolve_selected_dataset_id
from services.silver_gold_outputs_service import load_silver_gold_summary


dash.register_page(
    __name__,
    path="/silver-gold-outputs",
    name="Silver & Gold Outputs",
    title="Silver & Gold Outputs - LiDAR Platform",
)


REFRESH_INTERVAL_MS = 60_000


def _empty_alert(message, color="info"):
    return dbc.Alert(message, color=color, className="mb-0")


def _workflow_color(workflow_state):
    if workflow_state == "completed":
        return "success"
    if workflow_state in {"running", "partial"}:
        return "warning"
    if workflow_state == "failed":
        return "danger"
    return "info"


def _context_panel(summary):
    dataset_id = summary.get("dataset_id") or "Not selected"
    prep_version = summary.get("prep_version") or "Not available"
    rows = [
        ("Dataset ID", dataset_id),
        ("Prep Version", prep_version),
        ("Preprocessing Status", summary.get("preprocessing_status") or "Pending"),
        ("Silver Output Count", summary.get("silver_files", 0)),
        ("Gold Output Count", summary.get("gold_files", 0)),
        ("Gold Blocks", summary.get("gold_blocks", 0)),
        (
            "Gold Ready for Training",
            "Yes" if summary.get("gold_ready_for_training") else "No",
        ),
    ]

    split_availability = summary.get("split_availability") or {}
    rows.extend(
        [
            ("Train Blocks", "Available" if split_availability.get("train") else "Missing"),
            ("Val Blocks", "Available" if split_availability.get("val") else "Missing"),
            ("Test Blocks", "Available" if split_availability.get("test") else "Missing"),
        ]
    )

    message = summary.get("message")
    children = []
    if message:
        children.append(_empty_alert(message, _workflow_color(summary.get("workflow_state"))))
    children.append(
        html.Div(
            [
                info_card(
                    dataset_id,
                    "Silver and Gold status is derived from real output files only.",
                    "Selected Dataset",
                ),
                kv_grid(rows),
            ],
            className="ops-two-col",
        )
    )
    return html.Div(children, className="ops-stack")


def _contracts_panel(summary):
    return html.Div(
        [
            html.Div(
                [
                    info_card(
                        "Feature schema",
                        "Model-specific feature-channel contracts discovered from Gold metadata.",
                        "Gold",
                    ),
                    data_table(
                        summary.get("feature_schema"),
                        empty_title="No feature schema",
                        empty_detail="No model_configs.json artifact was found.",
                    ),
                ],
                className="ops-stack",
            ),
            html.Div(
                [
                    info_card(
                        "Label schema",
                        "Building/non-building label mapping discovered from Gold metadata.",
                        "Gold",
                    ),
                    data_table(
                        summary.get("label_schema"),
                        empty_title="No label schema",
                        empty_detail="No label_map.json artifact was found.",
                    ),
                ],
                className="ops-stack",
            ),
        ],
        className="ops-two-col",
    )


layout = page_shell(
    active="Outputs",
    subtitle="Silver cleaned data and Gold model-ready products",
    status="Data Products",
    canvas_id="silver-gold-cv",
    eyebrow="Data Management",
    title="Silver & Gold",
    accent="Outputs",
    description="Inspect cleaned Silver outputs and model-ready Gold blocks generated by the preprocessing pipeline.",
    metrics=[
        ("Dataset", "Live"),
        ("Preprocessing", "Live"),
        ("Silver Files", "Live"),
        ("Gold Ready", "Live"),
    ],
    page_class="silver-gold-page",
    children=[
        dcc.Interval(
            id="silver-gold-refresh",
            interval=REFRESH_INTERVAL_MS,
            n_intervals=0,
        ),
        section(
            "Selection",
            "Workflow status",
            "Dataset context is resolved from ?dataset_id=... first, then the session store.",
            html.Div(
                _empty_alert("Please select a dataset from Data Explorer first."),
                id="silver-gold-context",
            ),
            "ops-panel-primary",
        ),
        section(
            "Silver Layer",
            "Cleaned point-cloud outputs",
            "Read-only summary of real Silver artifacts generated by preprocessing.",
            html.Div(id="silver-gold-silver-table"),
        ),
        section(
            "Gold Layer",
            "Model-ready outputs",
            "Gold products are shown only when model-ready output files exist.",
            html.Div(id="silver-gold-gold-table"),
        ),
        section(
            "Contracts",
            "Feature and label schemas",
            "Feature-channel and class-mapping summaries are loaded from Gold metadata when available.",
            html.Div(id="silver-gold-contracts"),
        ),
        section(
            "Paths",
            "Manifest and output paths",
            "Canonical B2 v2 prefixes and local cache paths used for this selected dataset.",
            html.Div(id="silver-gold-paths"),
        ),
    ],
)


@callback(
    Output("silver-gold-context", "children"),
    Output("silver-gold-silver-table", "children"),
    Output("silver-gold-gold-table", "children"),
    Output("silver-gold-contracts", "children"),
    Output("silver-gold-paths", "children"),
    Input("selected-dataset-id", "data"),
    Input("url", "search"),
    Input("silver-gold-refresh", "n_intervals"),
)
def update_silver_gold_outputs(selected_dataset_id, search, _ticks):
    dataset_id = resolve_selected_dataset_id(search, selected_dataset_id)
    if not dataset_id:
        empty = _empty_alert("Please select a dataset from Data Explorer first.")
        empty_table = data_table(
            [],
            empty_title="No dataset selected",
            empty_detail="Please select a dataset from Data Explorer first.",
        )
        return empty, empty_table, empty_table, empty_table, empty_table

    summary = load_silver_gold_summary(dataset_id, include_airflow_status=True)
    silver_table = data_table(
        summary.get("silver"),
        empty_title="No Silver outputs",
        empty_detail=summary.get("message") or "No Silver files were found for this dataset.",
    )
    gold_table = data_table(
        summary.get("gold"),
        empty_title="No Gold outputs",
        empty_detail=summary.get("message") or "No Gold model-ready files were found for this dataset.",
    )
    paths_table = data_table(
        summary.get("paths"),
        empty_title="No output paths",
        empty_detail=summary.get("message") or "No output prefix could be resolved.",
    )
    return _context_panel(summary), silver_table, gold_table, _contracts_panel(summary), paths_table
